from __future__ import annotations

from pathlib import Path


def _quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def render_env_exports(values: dict[str, str]) -> str:
    lines = [
        "# Generated by `latch setup`.",
        "# Usage: source ./env.sh",
    ]
    for key, value in values.items():
        lines.append(f"export {key}={_quote(str(value))}")
    lines.append("")
    return "\n".join(lines)


def write_env_file(config_dir: Path, values: dict[str, str]) -> Path:
    path = config_dir / "env.sh"
    path.write_text(render_env_exports(values))
    return path
